# SPDX-License-Identifier: GPL-2.0-or-later
# Standalone DKMS registration for this repo, built directly -- no
# separate system76-dkms apt/PPA package needed. Named "clevo-acpi",
# not "system76", so it can never collide with a real system76-dkms
# apt install on the same machine.
PACKAGE_NAME="clevo-acpi"
PACKAGE_VERSION="0.2.0"
BUILT_MODULE_NAME[0]="system76"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILT_MODULE_NAME[1]="clevo-acpi"
BUILT_MODULE_LOCATION[1]="src/"
DEST_MODULE_LOCATION[1]="/updates/dkms"
MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"
AUTOINSTALL="yes"
